### ISSUE TITLE
Installation and Example

### ISSUE THREAD

**Issue by moradza** [TinkerTools/tinker-hp#11]
Do you have installation guide of tinker-hp and tutorial with ani models?

**Comment by louislagardere** [comment]
Hi, the code is already available in the Deep-HP branch (in the GPU directory) and we are preparing a tutorial with guidelines on how to install everything and a few examples, especially with ANI models. It will be available in a couple of weeks.

**Comment by louislagardere** [comment]
The paper is now accepted in Chemical Science: https://pubs.rsc.org/en/content/articlepdf/2023/sc/d2sc04815a
and you can find guidelines on how to install everything with examples: https://github.com/TinkerTools/tinker-hp/blob/master/GPU/Deep-HP.md
