### ISSUE TITLE
`--with-blaslib` of `configure` is confusing

### ISSUE THREAD

**Issue by e-kwsm** [TinkerTools/tinker-hp#16]
https://github.com/TinkerTools/tinker-hp/blob/23e9cb4e7862a5e2869b5cabdd2b1c5b538b16e5/v1.2/configure.ac#L329-L338

https://github.com/TinkerTools/tinker-hp/blob/23e9cb4e7862a5e2869b5cabdd2b1c5b538b16e5/v1.2/configure.ac#L401

These have the following issues:

- the option is actually controls LAPACK; why not `--with-lapacklib`?
- if `lapack` is passed, BLAS linkage flag of `-lrefblas`, not  `-lblas`, is forcibly used
- OpenBLAS e.g. is not supported

**Comment by lhjolly** [comment]
The option actually controls the BLAS perfume (lapack or MKL) , not specifically LAPACK. So, --with-blaslib
-lrefblas is the correct way to link 
We've never used OpenBLAS. We do use mkl or lapack. So, we support only what we are sure of
