### ISSUE TITLE
don't print out the running speed in GPU v1.2 of tinker-hp

### ISSUE THREAD

**Issue by Cynthia0807-learn** [TinkerTools/tinker-hp#17]
this is what printed out in end of my log file:
```
TINKER-HP is Exiting following Normal Termination
```
it doesn't print out ns/day. Which keyword can control the output of speed?

**Comment by louislagardere** [comment]
For that you need to add the line "verbose" in your *.key file

**Comment by Cynthia0807-learn** [comment]
I added it,but it doesn’t work.

**Comment by Cynthia0807-learn** [comment]
> For that you need to add the line "verbose" in your *.key file

I added it,but it doesn’t work.

**Comment by opadjoua** [comment]
Greetings,
Tinker-HP prints the dynamics report after a certain number of time steps controlled by the value of the printout variable, which by default is 100 for double precision and 1000 for mixed precision. It must be a multiple of 100, and can be adjusted using the keyfile. For instance, `printout   500`.
 Naturally, `verbose` keyword also need to be present.

**Comment by Cynthia0807-learn** [comment]
> Greetings, Tinker-HP prints the dynamics report after a certain number of time steps controlled by the value of the printout variable, which by default is 100 for double precision and 1000 for mixed precision. It must be a multiple of 100, and can be adjusted using the keyfile. For instance, `printout 500`. Naturally, `verbose` keyword also need to be present.

Thanks for your help.It works well now.
