### ISSUE TITLE
Facing a minor issue in compilation

### ISSUE THREAD

**Issue by heman3333** [TinkerTools/tinker-hp#18]
I am trying to compile the tinker-hp v1.2 codes in my Centos cluster. After configuration, when I am making the executables
by the command 'make -j', it is showing the following error:

decomp_2d.f90:16:6:

   use MPI
      1
Fatal Error: Cannot read module file ‘mpi.mod’ opened at (1), because it was created by a different version of GNU Fortran
compilation terminated.

I tried with other GNU version too, but the same error.
Kind suggestions are required.

Thanks !!

**Comment by lhjolly** [comment]
Hello heman3333,

The first thing I would suggest is,to make a make clean in the 2dcomp_fft directory.

To be able to help you, can you please tell me what configure command you used, and the output it gave ?

Kind regards,

**Comment by heman3333** [comment]
Hi lhjolly,
Thanks for responding.
Here is the command that I used for configuration:
 "./configure --enable-fft-mkl --with-fftlib=mkl "

And the output was that it gave, is following:

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for mpiicpc... no
checking for mpic++... mpic++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether mpic++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of mpic++... gcc3
checking for ranlib... ranlib
checking for tput... ok
checking for python... ok
checking whether ln -s works... yes
checking for mpiifort... no
checking for mpif90... mpif90
checking whether we are using the GNU Fortran compiler... yes
checking whether mpif90 accepts -g... yes
checking for mpiifort... no
checking for mpif90... mpif90
checking whether we are using the GNU Fortran 77 compiler... yes
checking whether mpif90 accepts -g... yes
configure: "mpif90 wrapper will be used to compile Tinker-HP"
checking for ifort... no
checking for pgfortran... no
checking for gfortran... gfortran
configure: "The wrapped compiler is gfortran"
checking for Fortran flag to compile preprocessed .F files... none
checking how to define symbols for preprocessed Fortran... -D
checking for Fortran flag needed to accept fixed-form source... none
checking for Fortran flag to enable array-bounds checking... -fcheck=bounds
checking what type of BLAS the user wants... 
checking for dgetrs in -lmkl_core... yes
checking what FFT Library the user wants... mkl
checking for dfftw_plan_dft_c2r_2d in -lmkl_core... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating 2decomp_fft/src/Makefile
config.status: creating example/Makefile
config.status: creating params/Makefile
config.status: creating source/Makefile
config.status: creating colvars/Makefile
config.status: creating tutorials/Makefile
config.status: creating tutorials/SMD/Makefile
config.status: creating tutorials/SMD/CFSMD/Makefile
config.status: creating tutorials/SMD/CVSMD/Makefile
config.status: creating scripts/Makefile
config.status: creating scripts/tinkerhp
config.status: executing depfiles commands
configure: 
configure: **********************************************************************
configure: **
configure: ** Running Mode         :    NORMAL (No extension for binaries)                             
configure: ** MPI Fortran Wrapper  : mpif90                                                                          
configure: ** Fortran Compiler     : gfortran                                                                        
configure: ** Fortran flags        : -cpp    -O3 -Wno-argument-mismatch  -C -fbacktrace                              
configure: **                      :                                                                                 
configure: ** 2decomp Library      : -L ../2decomp_fft/src/ -l2decomp_fft                                            
configure: ** PLUMED  Library      :                                                                                 
configure: ** PLUMED  Includes     :                                                                                 
configure: ** COLVARS  Library     :                                                                                 
configure: ** COLVARS  Includes    :                                                                                 
configure: ** TCL  Library         :                                                                                 
configure: ** TCL  Includes        :                                                                                 
configure: ** FFTW3 Interface      : mkl of the MKL library                                                          
configure: ** FFTW3 Path           : /home/heman/intel/oneapi/mkl/2023.1.0/lib/intel64                              
configure: ** FFTW3 Includes       : -I /home/heman/intel/oneapi/mkl/2023.1.0/include                               
configure: ** FFTW3 Library        : -Wl,--no-as-needed -lmkl_gf_lp64    -lmkl_sequential -lmkl_core -ldl            
configure: ** BLAS Type            : MKL                                                                             
configure: ** BLAS Path            : /home/heman/intel/oneapi/mkl/2023.1.0/lib/intel64                              
configure: ** Prefix installation  : /home/heman/softwares/tinker-hp/v1.2                                           
configure: ** Binaries location    : /home/heman/softwares/tinker-hp/v1.2/bin                                       
configure: **
configure: **********************************************************************
configure:

**Comment by heman3333** [comment]
Hi lhjolly, 
Thanks a lot for your kind help in solving this issue.
