### ISSUE TITLE
How to improve the performance of GPU

### ISSUE THREAD

**Issue by Cynthia0807-learn** [TinkerTools/tinker-hp#20]
I tested the system containing 8398 atoms. Tinker-HP run at approximately 14 ns/day, while Tinker9 achieved a speed of 55ns/day. How to increase the speed in tinker-hp, please?
My command:
`mpirun -np 1 dynamic.gpu 1scy_md.xyz -k md.key 5000 2 10 4 298 1.0 > md_tinker-hp.log`

**Comment by louislagardere** [comment]
It's probably because you are comparing the double precision version of Tinker-HP GPU (dynamic.gpu binary) vs mixed precision Tinker 9. If you used the installation script by default, the mixed precision binaries of Tinker-HP should have the ".mixed" suffix.

**Comment by Cynthia0807-learn** [comment]
> It's probably because you are comparing the double precision version of Tinker-HP GPU (dynamic.gpu binary) vs mixed precision Tinker 9. If you used the installation script by default, the mixed precision binaries of Tinker-HP should have the ".mixed" suffix.

I did use the installtion script by default,and it generated two binary file:dynamic.gpu and dynamic.fpa. Maybe because FPA was set to 1 in file install.sh? I tried dynamic.fpa, but it reported the error:
```
error getting device properties            35
 rank            0 Unknown device type
  update getDeviceProp routine for compute capability
```

**Comment by Cynthia0807-learn** [comment]
> > It's probably because you are comparing the double precision version of Tinker-HP GPU (dynamic.gpu binary) vs mixed precision Tinker 9. If you used the installation script by default, the mixed precision binaries of Tinker-HP should have the ".mixed" suffix.
> 
> I did use the installtion script by default,and it generated two binary file:dynamic.gpu and dynamic.fpa. Maybe because FPA was set to 1 in file install.sh? I tried dynamic.fpa, but it reported the error:
> 
> ```
> error getting device properties            35
>  rank            0 Unknown device type
>   update getDeviceProp routine for compute capability
> ```

Sorry.I didn't login the computing node with GPU

**Comment by Cynthia0807-learn** [comment]
> > > It's probably because you are comparing the double precision version of Tinker-HP GPU (dynamic.gpu binary) vs mixed precision Tinker 9. If you used the installation script by default, the mixed precision binaries of Tinker-HP should have the ".mixed" suffix.
> > 
> > 
> > I did use the installtion script by default,and it generated two binary file:dynamic.gpu and dynamic.fpa. Maybe because FPA was set to 1 in file install.sh? I tried dynamic.fpa, but it reported the error:
> > ```
> > error getting device properties            35
> >  rank            0 Unknown device type
> >   update getDeviceProp routine for compute capability
> > ```
> 
> Sorry.I didn't login the computing node with GPU

However, I used `dynamic.mixed` and `dynamic.fpa`,it reported the error again:
```
FATAL ERROR: data in PRESENT clause was not found on device 1: name=matb_lst$p host:0x861c080
 file:/export/home/yqwang/software/tinker-hp/GPU/build0/nblistgpu.f build_adjacency_matrix line:1616
```
When I used `dynamic.gpu`，it worked normally.Why?

My installation environment:
```
export NVHPC_DIR=/export/home/yqwang/software/hpc_sdk_21.9/Linux_x86_64/21.9
export PATH=$NVHPC_DIR/comm_libs/mpi/bin:$NVHPC_DIR/compilers/bin:$PATH
export MANPATH=$MANPATH:$NVHPC_DIR/comm_libs/mpi/man
export LD_LIBRARY_PATH=$NVHPC_DIR/math_libs/lib64:$NVHPC_DIR/compilers/lib:$LD_LIBRARY_PATH
export PATH=/export/home/yqwang/software/gcc-8.3.0/bin:$PATH
export LD_LIBRARY_PATH=/export/home/yqwang/software/gmp-6.1.0/lib:/export/home/yqwang/software/mpfr-3.1.4/lib:/export/home/yqwang/software/mpc-1.0.3/lib:/export/home/yqwang/software/gcc-8.3.0/lib:/export/home/yqwang/software/gcc-8.3.0/lib64:$LD_LIBRARY_PATH
export C_INCLUDE_PATH=/export/home/yqwang/software/gcc-8.3.0/include:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=/export/home/yqwang/software/gcc-8.3.0/include:$CPLUS_INCLUDE_PATH
export PATH=/export/home/yqwang/software/binutils/bin:$PATH
```

**Comment by opadjoua** [comment]
Hello,
Since you are using the 21.9 version, I recommend you uncomment the `line 40` inside [ci/install.sh](https://github.com/TinkerTools/tinker-hp/blob/master/GPU/ci/install.sh), and restart the compilation.
This problem is documented inside the compiler section within the [Prerequisites.md](https://github.com/TinkerTools/tinker-hp/blob/master/GPU/Prerequisites.md) file

**Comment by Cynthia0807-learn** [comment]
> Hello, Since you are using the 21.9 version, I recommend you uncomment the `line 40` inside [ci/install.sh](https://github.com/TinkerTools/tinker-hp/blob/master/GPU/ci/install.sh), and restart the compilation. This problem is documented inside the compiler section within the [Prerequisites.md](https://github.com/TinkerTools/tinker-hp/blob/master/GPU/Prerequisites.md) file

Thanks for your help.Now it worked normally.
