### ISSUE TITLE
System Divergence During Molecular Dynamics Simulations

### ISSUE THREAD

**Issue by H6rst0n** [TinkerTools/tinker-hp#21]
It is easy to get system divergence when performing molecular dynamics simulation using the dynamic function of Tinker-HP version 1.2.
When performing molecular dynamics simulation, there are often abnormalities in energy, temperature, volume, etc. I suspect that this is a problem with the coordinates (the coordinates of the output arc file are quite unreasonable).
And the following error will appear:
"Warning, system moved too much since last neighbor list update, try lowering nlupdate VDW"
Then the program will crash and the simulation will be terminated.

The strange thing is that when using the same input file (Tinker xyz, key file) to perform molecular dynamics simulation in Tinker-8 dynamic, this situation does not occur, so I am not sure whether this situation is caused by parallelization?

**Comment by H6rst0n** [comment]
> It is easy to get system divergence when performing molecular dynamics simulation using the dynamic function of Tinker-HP version 1.2. When performing molecular dynamics simulation, there are often abnormalities in energy, temperature, volume, etc. I suspect that this is a problem with the coordinates (the coordinates of the output arc file are quite unreasonable). And the following error will appear: "Warning, system moved too much since last neighbor list update, try lowering nlupdate VDW" Then the program will crash and the simulation will be terminated.
> 
> The strange thing is that when using the same input file (Tinker xyz, key file) to perform molecular dynamics simulation in Tinker-8 dynamic, this situation does not occur, so I am not sure whether this situation is caused by parallelization?

**Comment by H6rst0n** [comment]
Let me add that the system being simulated is a periodic liquid system, and the force field used is mmff.prm. Later, I found out from previous discussions that the mmff of Tinker-HP and Tinker-8 seem to be a bit different(?).
Even if the mmff.prm of Tinker-HP is used, the following error will still appear during the simulation and the simulation will be terminated.
`Warning, system moved too much since last neighbor list update, try lowering nlupdate VDW`

**Comment by louislagardere** [comment]
Hello, there can be many things that affect the stability of your MD simulation and some of the options of Tinker 8 are not ported within Tinker-HP, can you share some representative input so that I can run some tests ?

**Comment by jayponder** [comment]
I'm not sure what the difference in stability between Tinker8 and Tinker-HP might be. 

However, MMFF should never be used for MD simulation. That force field is OK for conformational analysis, and generally for energy minimization of isolated molecules. But it was never intended for use in MD simulation. Any MD results you do get with MMFF will typically be very poor (densities off by 20% and more, bad heat of vaporization values, etc.). And many liquid simulations will simply be unstable when using MMFF. Bill Jorgensen actually published a paper in the mid-1990's showing just how poor MMFF was when trying to use if for MD; see Journal of Physical Chemistry, 100, 18010-18013 (1996).

**Comment by H6rst0n** [comment]
Hi, thanks for the quick responses @louislagardere and @jayponder,

@louislagardere I have added `VDW-CORRECTION` and `EWALD` to the key file to describe the longer-range interactions, but it seems that the problem comes from the force field I used.

Thanks a lot for the reminder @jayponder , I have also seen some discussions about MMFF not being suitable for MD simulations, but I didn't expect it to be so inaccurate, thanks for your reply. I took a closer look at the energy distribution and found that most of it comes from VDW, so it is possible that the instability of the calculation comes from my wrong choice of force field

**Comment by jayponder** [comment]
Yes, the biggest "problem" with MMFF for MD is with the vow parameters, which seem to systematically be too big for use in liquid simulation. However, you can't just make the vdw values smaller, as that will break all the other interactions that are carefully calibrated in MMFF (such as hydrogen bonds, etc.). So MMFF should only be used for conformational analysis of isolated drug-like molecules- which is what Tom Halgren and the other developers at Merck in the early 1990's intended it for.

If you want to do general liquid simulations with a "simple" force field, it is hard to beat OPLS-AA. And the Jorgensen lab has put a generic parameter server on the internet. Look for the LIgParGen web site; it even writes parameter files compatible with the Tinker software :)

**Comment by H6rst0n** [comment]
Wow! Thank you for such a great website, it helps me a lot.
