### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by mayank-kohli** [TinkerTools/tinker-hp#22]
Hi, 

I have tried the docker and the example files from the nvidia website.
I have a system 2wth 4 gpus rtx 2080 ti.

The submission was done but it is showing me a performance of 0.6ns/day.

Is this number correct or I am missing something during submission, as it is utilizing all 4 gpus.

I used cox system for this run.

Thank you

**Comment by louislagardere** [comment]
Hi,
The Cox system is too small to make use of 4 rtx 2080 ti, all the more without any nvlink connection between them, so you should only use 1 gpu for this system.
With the version of the nvidia website we get 3.59 ns/day with the respa integrator and a 2fs timestep and 7.56 ns/day with the baoabrespa1 integrator and a 10fs timestep (with heavy hydrogens) on a RTX 2080 TI.

**Comment by mayank-kohli** [comment]
Thank you for the reply, it clears my doubts.
