### ISSUE TITLE
Including a patch for SAVE-FORCE command for the dynamic executable for Tinker-HP v1.2

### ISSUE THREAD

**Issue by ovr4** [TinkerTools/tinker-hp#8]
Hello,

I was wondering if you would be able to include a patch to the current dynamic executable that would allow the save-force command (which generates .frc files) to also write the forces for the inactive atoms in simulations. Currently, the save force command displays the forces for inactive atoms as 0 i.e. 0 0 0 in x y z. But I would like the command to also report the non-zero forces acting on these inactive atoms due to their interaction with the other active atoms in the simulation. Please let me know if this would be an easy patch to include for tinker-hp v1.2 in its current form.

**Comment by louislagardere** [comment]
Hi,
This was quite straightforward: the forces were deduced from the accelerations hence no force for inactive atoms but now there are directly printed so you will see valus even if they are not applied for integration.
