### ISSUE TITLE
problem with running tinker on MMFF94 files

### ISSUE THREAD

**Issue by andrzejdoro** [TinkerTools/tinker-hp#9]
Hello,
In our HPC centre, one of our users is trying to test Tinker-HP on **mmff.prm** file.
However, it fails on both v1.1 and v1.2 versions.

We have investigated this issue and presumably found bugs in the code.
Below, I'm pasting two tracebacks from v1.1 (for v1.2 they look very similar).

Traceback 1:

```
forrtl: severe (408): fort: (2): Subscript #2 of the array IBND has value 280 which is greater than the upper bound of 279

Image              PC                Routine            Line        Source             
libifcoremt.so.5   00002AAAB1A9A0C3  for_emit_diagnost     Unknown  Unknown
dynamic            00000000007BE997  kanglem_                  682  kangle.f
dynamic            00000000007B10A4  kangle_                   312  kangle.f
dynamic            0000000000558BF7  mechanic_                  64  mechanic.f
dynamic            00000000004038E0  dynamic_bis_               80  dynamic.f
dynamic            0000000000402E0E  MAIN__                     24  dynamic.f
dynamic            0000000000402D8E  Unknown               Unknown  Unknown
libc-2.17.so       00002AAAB3754555  __libc_start_main     Unknown  Unknown
dynamic            0000000000402C59  Unknown               Unknown  Unknown
```

Traceback 2:

```
forrtl: severe (408): fort: (7): Attempt to use pointer IOPB when it is not associated with a target

Image              PC                Routine            Line        Source             
libifcoremt.so.5   00002B76D3FFE0C3  for_emit_diagnost     Unknown  Unknown
dynamic            000000000085CA84  kopbendm_                 437  kopbend.f
dynamic            000000000085791E  kopbend_                  116  kopbend.f
dynamic            0000000000558C57  mechanic_                  71  mechanic.f
dynamic            0000000000403950  dynamic_bis_               80  dynamic.f
dynamic            0000000000402E7E  MAIN__                     24  dynamic.f
dynamic            0000000000402DFE  Unknown               Unknown  Unknown
libc-2.17.so       00002B76D5CB8555  __libc_start_main     Unknown  Unknown
dynamic            0000000000402CC9  Unknown               Unknown  Unknown
```

In the first case, we have found that:

- in kanglem the loop is going from `1` to `maxbnd`
(https://github.com/TinkerTools/tinker-hp/blob/master/v1.1/source/kangle.f#L681) 

- the `maxbnd` is equal to `4*n`
(https://github.com/TinkerTools/tinker-hp/blob/master/v1.1/source/readxyz.f#L106)

- the size of the second dimension of `ibnd` array is `nbond`
(https://github.com/TinkerTools/tinker-hp/blob/master/v1.1/source/bonds.f#L196)

- finally, `nbond` cannot be greater than `4*n`
(https://github.com/TinkerTools/tinker-hp/blob/master/v1.1/source/bonds.f#L43)

In the second case (next error after fixing loop range in kanglem):

- in the kopbend subroutine in init phase, for `forcefield == "MMFF94"` a kopbendm is called
https://github.com/TinkerTools/tinker-hp/blob/master/v1.1/source/kopbend.f#L115

- it is called before `call alloc_shared_opbend` which is allocating `iopb` array

- and this is why in the first access to `iopb` in kopbendm we receive the above error
(https://github.com/TinkerTools/tinker-hp/blob/master/v1.1/source/kopbend.f#L437)

Please, take a look at handling forcefield equal to "MMFF94" and consider some fixes.
If there is something wrong on our side, we would be grateful if you can provide some working example with "mmff" file.

Best regards,
Andrzej Dorobisz

**Comment by louislagardere** [comment]
Thanks for noting this, it is indeed a bug with an easy fix, can you provide your input files so that I can make some tests on my end ?

**Comment by andrzejdoro** [comment]
We were testing on mmff.prm file from the repo (https://github.com/TinkerTools/tinker-hp/blob/master/v1.1/params/mmff.prm).
I will ask our user if I'm allowed to submit txyz file.

**Comment by andrzejdoro** [comment]
Here are the input files:
[mmff-test.zip](https://github.com/TinkerTools/tinker-hp/files/7927357/mmff-test.zip)

**Comment by louislagardere** [comment]
Thanks for the files, I just pushed a fixed for the mmff force field.
